// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4WamSK_Y8fao3Esc-YYsEr1qKeZInbM',
    appId: '1:85566463938:web:7012d93d2c33d4c6dbc05b',
    messagingSenderId: '85566463938',
    projectId: 'test2024-8ad72',
    authDomain: 'test2024-8ad72.firebaseapp.com',
    storageBucket: 'test2024-8ad72.appspot.com',
    measurementId: 'G-44KW278SFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplL5nvxocn2cRTgu-kRSO330jah_t8yU',
    appId: '1:85566463938:android:8aa7199eb2281e62dbc05b',
    messagingSenderId: '85566463938',
    projectId: 'test2024-8ad72',
    storageBucket: 'test2024-8ad72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7NDgydzPwCZ3Te84ySwm1sJU89exEdw',
    appId: '1:85566463938:ios:62da036231459a43dbc05b',
    messagingSenderId: '85566463938',
    projectId: 'test2024-8ad72',
    storageBucket: 'test2024-8ad72.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7NDgydzPwCZ3Te84ySwm1sJU89exEdw',
    appId: '1:85566463938:ios:62da036231459a43dbc05b',
    messagingSenderId: '85566463938',
    projectId: 'test2024-8ad72',
    storageBucket: 'test2024-8ad72.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE4WamSK_Y8fao3Esc-YYsEr1qKeZInbM',
    appId: '1:85566463938:web:131ba7f28925887edbc05b',
    messagingSenderId: '85566463938',
    projectId: 'test2024-8ad72',
    authDomain: 'test2024-8ad72.firebaseapp.com',
    storageBucket: 'test2024-8ad72.appspot.com',
    measurementId: 'G-214Y3FSTX2',
  );
}
